version: '3.8'

services:
  db:
    build: .
    container_name: eka_postgres
    environment:
      POSTGRES_DB: eka_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: eka_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/storage:/data

  redis:
    image: redis:alpine
    container_name: eka_redis
    ports:
      - "6379:6379"
