[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eka-oci"
version = "0.1.0"
dependencies = [
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic-settings",
    "fastapi",
    "uvicorn",
    "alembic",
    "pgvector",
    "python-dotenv",
    "python-multipart",
    "orjson"

]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
